"use client";
import Footer from "@/components/Footer/Footer";
import NavigationDesktop from "@/components/Navigation/NavigationDesktop";
import NavigationMobile from "@/components/Navigation/NavigationMobile";
import { CartContextProvider } from "./api/cartContext";
import "./globals.css";
import { useState, useEffect } from "react";
import CookieAlert from "@/components/CookieAlert/CookieAlert";
import Cookies from "js-cookie";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [cookiesAllowed, setCookiesAllowed] = useState(true);
  let cookiesExist = false;
  useEffect(() => {
    const isAllowedCookie = Cookies.get("cookiesAllowed");
    if (isAllowedCookie) cookiesExist = true;
    setCookiesAllowed(cookiesExist);
  }, [cookiesAllowed]);

  return (
    <CartContextProvider>
      <head>
        <script
          src="https://kit.fontawesome.com/f141ac3909.js"
          crossorigin="anonymous"
        ></script>
      </head>
      <html lang="en">
        <body className="4xl:container mx-auto">
          {" "}
          {!cookiesAllowed && !cookiesExist && (
            <CookieAlert
              handleAcceptCookies={() => {
                setCookiesAllowed(true);
                Cookies.set("cookiesAllowed", true, { expires: 365 });
              }}
            />
          )}
          <NavigationDesktop />
          <NavigationMobile />
          {children}
          <Footer />
        </body>
      </html>
    </CartContextProvider>
  );
}
