import Footer from "@/components/Footer/Footer";
import NavigationDesktop from "@/components/Navigation/NavigationDesktop";
import NavigationMobile from "@/components/Navigation/NavigationMobile";
import { CartContextProvider } from "./api/cartContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartContextProvider>
      <head>
        <script
          src="https://kit.fontawesome.com/f141ac3909.js"
          crossorigin="anonymous"
        ></script>
      </head>
      <html lang="en">
        <body className="4xl:container mx-auto">
          <NavigationDesktop />
          <NavigationMobile />
          {children}
          <Footer />
        </body>
      </html>
    </CartContextProvider>
  );
}
